This code has been taken and adapted from the Udacity Github Repository
---
apiVersion: v1
data:
  mapRoles: |
      - groups:
        - system:bootstrappers
        - system:nodes
        rolearn: arn:aws:iam::716000321728:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R432JAMEY4GH
        username: system:node:{{EC2PrivateDNSName}}
      - groups:
        - system:masters
        rolearn: arn:aws:iam::716000321728:role/UdacityFlaskDeployCBKubectlRole
        username: build
  mapUsers: "[]\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-01T23:03:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1496"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ae5dadc9-7a6e-4a6c-b3df-edda14dbe595
